services:
  # Weaviate vector database
  weaviate:
    command:
      - --host
      - 0.0.0.0
      - --port
      - '8080'
      - --scheme
      - http
    image: cr.weaviate.io/semitechnologies/weaviate:1.30.0
    container_name: rag-weaviate
    restart: on-failure:0
    ports:
      - "8080:8080"
      - "50051:50051"
    environment:
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
      ENABLE_API_BASED_MODULES: 'true'
      CLUSTER_HOSTNAME: 'node1'
    volumes:
      - weaviate_data:/var/lib/weaviate
    networks:
      - rag-network

  # RAG Application API
  rag-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rag-api
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      # API Configuration
      API_HOST: 0.0.0.0
      API_PORT: 8000
      
      # Weaviate Configuration (use container name for internal networking)
      WEAVIATE_URL: http://weaviate:8080
      
      # Load other variables from .env file
      API_BEARER_TOKEN: ${API_BEARER_TOKEN}
      GOOGLE_API_KEY: ${GOOGLE_API_KEY}
      LLM_MODEL: ${LLM_MODEL:-gemini-2.5-flash}
      WEAVIATE_CLASS_NAME: ${WEAVIATE_CLASS_NAME:-DocumentChunks}
      EMBEDDING_MODEL: ${EMBEDDING_MODEL:-all-MiniLM-L6-v2}
      MIN_CHUNK_SIZE: ${MIN_CHUNK_SIZE:-100}
      MAX_CHUNK_SIZE: ${MAX_CHUNK_SIZE:-1000}
      CHUNK_OVERLAP_PERCENTAGE: ${CHUNK_OVERLAP_PERCENTAGE:-5}
      LOG_LEVEL: ${LOG_LEVEL:-INFO}
      LOG_FILE: ${LOG_FILE:-/tmp/app.log}
      DISABLE_FILE_LOGGING: ${DISABLE_FILE_LOGGING:-false}
      MAX_WORKERS: ${MAX_WORKERS:-8}
      RETRIEVAL_TOP_K: ${RETRIEVAL_TOP_K:-7}
    volumes:
      # Mount temporary directories (optional, for debugging)
      - ./temp:/app/temp
      - ./downloads:/app/downloads
      - ./cache:/app/cache
      # Create a named volume for logs instead of bind mount
      - rag_logs:/tmp
    networks:
      - rag-network
    depends_on:
      - weaviate
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 120s

networks:
  rag-network:
    driver: bridge
    name: rag-network

volumes:
  weaviate_data:
    name: rag-weaviate-data
    driver: local
  rag_logs:
    name: rag-logs
    driver: local
