version: '3.8'
services:
  rag-api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - ./huggingface_cache:/app/huggingface_cache
    environment:
      - w=weaviate
      - WEAVIATE_PORT=8080
      - WEAVIATE_GRPC_PORT=50051
      - PYTHONPATH=/app
    depends_on:
      - weaviate
    restart: unless-stopped
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
    networks:
      - hackrx-net

  weaviate:
    command:
      - --host
      - 0.0.0.0
      - --port
      - '8080'
      - --scheme
      - http
    image: cr.weaviate.io/semitechnologies/weaviate:1.32.2
    ports:
      - 8080:8080
      - 50051:50051
    volumes:
      - weaviate_data:/var/lib/weaviate
    restart: unless-stopped
    environment:
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
      ENABLE_API_BASED_MODULES: 'true'
      CLUSTER_HOSTNAME: 'disable'       # Prevent accidental clustering
      CLUSTER_GOSSIP_BIND_PORT: '0'     # Disable gossip port
      CLUSTER_DATA_BIND_PORT: '0'       # Disable RAFT port
    networks:
      - hackrx-net

volumes:
  weaviate_data:

networks:
  hackrx-net:
    driver: bridge
