


version: '3.8'
services:
  llmsherpa:
    image: ghcr.io/nlmatics/nlm-ingestor:latest
    ports:
      - "5010:5001"
    restart: always

  app:
    build: .
    ports:
      - "1212:1212"
    depends_on:
      - llmsherpa
      - weaviate
    volumes:
      - ./app:/app
    environment:
      - LLMSHERPA_API_URL=http://llmsherpa:5001/api/parseDocument?renderFormat=all&applyOcr=yes&useNewIndentParser=yes
      - WEAVIATE_URL=http://weaviate:8080
    restart: always

  weaviate:
    image: semitechnologies/weaviate:1.25.3
    ports:
      - "8080:8080"
    environment:
      - QUERY_DEFAULTS_LIMIT=25
      - AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED=true
      - PERSISTENCE_DATA_PATH=/var/lib/weaviate
      - DEFAULT_VECTORIZER_MODULE=none
      - CLUSTER_HOSTNAME=none
    volumes:
      - weaviate_data:/var/lib/weaviate
    restart: always
volumes:
  weaviate_data:
